import { Geist, Geist_Mono,Montserrat,Oxanium,Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ['400', '700'], 
  variable: "--font-roboto",
  subsets: ["latin"],
});
const oxanium=Oxanium({
  weight: ['400', '700'], 
  variable: "--font-oxanium",
  subsets: ["latin"],
})
const montserrat=Montserrat({
  weight: ['400', '700'], 
  variable: "--font-montserrat",
  subsets: ["latin"],
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${oxanium.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
